// Встречи (SPEC §8): nine starter scenes. Each has an opening line from the character and three
// exchanges: the character's reply that follows the learner's answer (the last one closes the
// scene), a Russian hint of what to achieve, and a model answer for the scripted mode without AI.
import type { SceneDef } from '@/types'

export const seedScenes: SceneDef[] = [
  {
    id: 'landlord',
    title: 'Арендодатель',
    emoji: '🏠',
    settingRu: 'Ты снимаешь квартиру. Хозяин хочет поднять цену на 15% с следующего месяца.',
    settingEn: 'The learner rents a flat; the landlord wants to raise the rent by 15% from next month.',
    goalRu: 'Договориться о меньшем повышении или об отсрочке.',
    goalEn: 'Negotiate a smaller increase or a delay.',
    character: 'Mr. Adams, a polite but firm landlord',
    opening: 'Hi! Thanks for coming. As I mentioned, I have to raise the rent by fifteen percent from next month. Prices everywhere are going up.',
    turns: [
      { npcLine: 'I understand, but my costs have gone up too. What would work for you?', hintRu: 'Скажи, что понимаешь, но 15% для тебя слишком много. Спроси, можно ли меньше.', sampleEn: "I understand, but to be honest, fifteen percent is a lot for me. Could we talk about a smaller increase?" },
      { npcLine: "Hmm. Seven percent is tight for me. What if we do ten, but only from the month after next?", hintRu: 'Предложи конкретную цифру и напомни, что ты всегда платишь вовремя.', sampleEn: "I've always paid on time, so I was hoping for something like seven percent. That would be fair for both of us." },
      { npcLine: "Alright, ten percent from the month after next. Deal. Thanks for being straight with me.", hintRu: 'Согласись на компромисс и поблагодари.', sampleEn: 'That sounds fair. Let’s go with ten percent from the month after next. Thanks for meeting me halfway.' },
    ],
  },
  {
    id: 'passport',
    title: 'Паспортный контроль',
    emoji: '🛂',
    settingRu: 'Ты прилетел на неделю. Офицер на паспортном контроле задаёт вопросы о поездке.',
    settingEn: 'The learner has just landed for a week; a border officer asks about the trip.',
    goalRu: 'Коротко и ясно объяснить цель поездки, где живёшь и когда улетаешь.',
    goalEn: 'Explain clearly the purpose of the visit, the accommodation and the return date.',
    character: 'a calm border officer who asks short questions',
    opening: 'Good afternoon. Passport, please. What is the purpose of your visit?',
    turns: [
      { npcLine: 'I see. And where are you staying?', hintRu: 'Скажи, что приехал как турист на неделю.', sampleEn: "I'm here on holiday for a week. I'm going to see the city and visit a couple of friends." },
      { npcLine: 'How long are you planning to stay, and do you have a return ticket?', hintRu: 'Назови отель или адрес друзей.', sampleEn: "I'm staying at a hotel in the city centre, the Grand Hotel on Main Street." },
      { npcLine: 'Thank you. Enjoy your stay.', hintRu: 'Назови дату вылета и скажи, что обратный билет есть.', sampleEn: "I'm leaving next Sunday, the twelfth. Yes, I have a return ticket, here it is." },
    ],
  },
  {
    id: 'bar',
    title: 'Незнакомец в баре',
    emoji: '🍻',
    settingRu: 'Ты ждёшь друга в баре. Рядом садится человек и заводит разговор.',
    settingEn: 'The learner is waiting for a friend in a bar; a stranger starts a chat.',
    goalRu: 'Поддержать лёгкий small talk: откуда ты, чем занимаешься, что думаешь о городе.',
    goalEn: 'Keep a light small talk going: where you are from, what you do, what you think of the city.',
    character: 'Sam, a friendly local who likes to chat',
    opening: "Hey, mind if I sit here? Busy tonight, huh. I'm Sam. You're not from around here, are you?",
    turns: [
      { npcLine: "Nice! What brings you here, work or fun?", hintRu: 'Представься, скажи, откуда ты, и что ждёшь друга.', sampleEn: "Hi Sam, I'm Ramin. No, I'm from Baku. I'm just waiting for a friend, he's running late as usual." },
      { npcLine: "Cool. So what do you do, if you don't mind me asking?", hintRu: 'Скажи, зачем ты здесь, и спроси что-нибудь в ответ.', sampleEn: "A bit of both, to be honest. I'm here for a conference, but I wanted to see the city too. Have you always lived here?" },
      { npcLine: "Sounds interesting. Well, enjoy your evening, and say hi to your friend!", hintRu: 'Коротко расскажи о работе простыми словами.', sampleEn: "I'm in tech. I build apps, mostly for phones. It sounds boring, but I actually enjoy it." },
    ],
  },
  {
    id: 'series',
    title: 'Любимый сериал',
    emoji: '📺',
    settingRu: 'Друг не хочет смотреть твой любимый сериал: говорит, что это скучно.',
    settingEn: "A friend refuses to watch the learner's favourite series, calling it boring.",
    goalRu: 'Уговорить друга дать сериалу шанс.',
    goalEn: 'Persuade the friend to give the series a chance.',
    character: 'Alex, a sceptical friend with little free time',
    opening: "No way, I'm not watching that. Everyone says the first season is boring and nothing happens.",
    turns: [
      { npcLine: "Okay, but I only have one evening a week. Why should I spend it on this?", hintRu: 'Признай, что начало медленное, но объясни, чем сериал цепляет.', sampleEn: "I get it, the first two episodes are slow. But after that it really picks up, and the characters are great." },
      { npcLine: "Hmm, three episodes is a lot. What if I hate it?", hintRu: 'Предложи сделку: посмотреть три серии вместе.', sampleEn: "Let's make a deal: we watch three episodes together, and if you still hate it, I'll never mention it again." },
      { npcLine: "Fine, you win. Friday night, your place, and you're buying the pizza.", hintRu: 'Пообещай, что он не пожалеет, и договорись о времени.', sampleEn: "Then you can stop, no hard feelings. But trust me, you won't. How about Friday night?" },
    ],
  },
  {
    id: 'project',
    title: 'Рассказ о проекте',
    emoji: '💡',
    settingRu: 'На семейном ужине родственник не из IT спрашивает, над чем ты работаешь.',
    settingEn: 'At a family dinner a relative who is not in IT asks what the learner is working on.',
    goalRu: 'Объяснить проект простыми словами, без терминов.',
    goalEn: 'Explain the project in simple words, without jargon.',
    character: 'Aunt Maria, curious but not technical',
    opening: "So, I hear you're building something at work. What is it? Explain it to me like I'm five.",
    turns: [
      { npcLine: "Okay, but who needs that? Who would use it?", hintRu: 'Опиши, что делает продукт, одним простым сравнением.', sampleEn: "It's an app that helps people learn English, a bit like a game where every phrase is a small monster you have to beat." },
      { npcLine: "And what do you actually do all day? Just type?", hintRu: 'Скажи, кому это нужно и зачем.', sampleEn: "People who already know some English but freeze when they have to speak. It helps them practise every day without getting bored." },
      { npcLine: "Well, it sounds like you enjoy it. I'm proud of you. Pass the salad.", hintRu: 'Расскажи о своём дне просто и честно.', sampleEn: "A lot of it is thinking and talking to people, actually. I plan features, write code, and test them on my phone." },
    ],
  },
  {
    id: 'cafe',
    title: 'Вернуть заказ',
    emoji: '☕',
    settingRu: 'В кафе принесли не то, что ты заказал, и кофе холодный.',
    settingEn: 'In a cafe the learner got the wrong dish and a cold coffee.',
    goalRu: 'Вежливо вернуть заказ и получить правильный.',
    goalEn: 'Politely return the order and get the right one.',
    character: 'a busy but friendly waiter',
    opening: "Here you go, one chicken sandwich and a cappuccino. Enjoy!",
    turns: [
      { npcLine: "Oh, I'm so sorry about that. Let me check your order again.", hintRu: 'Скажи, что заказывал другое, и что кофе холодный.', sampleEn: "Sorry, I think there's been a mistake. I ordered the veggie sandwich, and the coffee is cold, I'm afraid." },
      { npcLine: "You're right, that's my fault. I'll bring the veggie sandwich and a fresh cappuccino. Anything else?", hintRu: 'Попроси заменить и уточни, сколько это займёт.', sampleEn: "No worries. Could you replace them? And how long will it take? I have a meeting in half an hour." },
      { npcLine: "Of course, it's on the house. Five minutes, I promise.", hintRu: 'Поблагодари и вежливо спроси про скидку или кофе за счёт заведения.', sampleEn: "Thanks a lot. And would it be possible to get the coffee on the house, since it was cold?" },
    ],
  },
  {
    id: 'philosophy',
    title: 'Простой спор',
    emoji: '🤔',
    settingRu: 'Коллега за обедом утверждает, что деньги не делают людей счастливее.',
    settingEn: 'A colleague at lunch claims money does not make people happier.',
    goalRu: 'Поспорить вежливо: согласиться частично и привести свой аргумент.',
    goalEn: 'Disagree politely: agree partly and give your own argument.',
    character: 'Dana, a colleague who enjoys a friendly argument',
    opening: "I honestly think money doesn't make anyone happier. Once you have enough for food and rent, the rest changes nothing.",
    turns: [
      { npcLine: "Okay, but studies say happiness stops growing after a certain income. Doesn't that prove my point?", hintRu: 'Частично согласись, но скажи, что деньги дают свободу выбора.', sampleEn: "I see your point, but I don't fully agree. Money doesn't buy happiness, but it gives you choices, and choices matter." },
      { npcLine: "Fair enough. So where's the line for you?", hintRu: 'Приведи пример из жизни: что деньги позволили тебе изменить.', sampleEn: "Maybe, but for example, money let me quit a job I hated. That changed my life more than any raise." },
      { npcLine: "Ha, I like that. Alright, you've half convinced me. Let's get dessert.", hintRu: 'Подведи итог: дело не в сумме, а в том, что она даёт.', sampleEn: "I guess it depends on what you do with it. It's not the amount, it's the freedom it gives you." },
    ],
  },
  {
    id: 'badnews',
    title: 'Созвон с плохими новостями',
    emoji: '📉',
    settingRu: 'Рабочий созвон. Ты должен сказать заказчику, что релиз задержится на две недели.',
    settingEn: 'A work call: the learner must tell the client the release will slip by two weeks.',
    goalRu: 'Честно сообщить о задержке, объяснить причину и предложить план.',
    goalEn: 'Deliver the delay honestly, explain the reason and offer a plan.',
    character: 'Mr. Lee, a client who dislikes surprises',
    opening: "Hi, thanks for the call. So, are we still on track for the release on the first?",
    turns: [
      { npcLine: "Two weeks? That's a problem. What happened?", hintRu: 'Скажи прямо, что релиз сдвигается на две недели.', sampleEn: "Thanks for taking the call. I have to be honest with you: the release will be about two weeks late." },
      { npcLine: "I appreciate you telling me early. What are you going to do about it?", hintRu: 'Объясни причину без оправданий.', sampleEn: "We found a serious bug in payments during testing. We'd rather fix it properly than ship something broken." },
      { npcLine: "Okay. Send me the plan today, and let's talk again on Monday.", hintRu: 'Предложи план и следующий шаг.', sampleEn: "Here's the plan: we fix the bug this week, test next week, and I'll send you a short update every two days." },
    ],
  },
  {
    id: 'interview',
    title: 'Лёгкое собеседование',
    emoji: '🎤',
    settingRu: 'Короткое знакомство с рекрутером: расскажи о себе и почему тебе интересна вакансия.',
    settingEn: 'A short screening call with a recruiter: introduce yourself and say why the role interests you.',
    goalRu: 'Представиться, рассказать об опыте и задать вопрос.',
    goalEn: 'Introduce yourself, describe your experience and ask a question.',
    character: 'Nina, a friendly recruiter',
    opening: "Hi! Nice to meet you. Let's keep this casual. Could you tell me a bit about yourself?",
    turns: [
      { npcLine: "Great. And why does this role interest you?", hintRu: 'Коротко: кто ты, чем занимаешься, сколько лет.', sampleEn: "Sure. I'm a developer with about six years of experience, mostly mobile apps. Right now I lead a small team." },
      { npcLine: "That makes sense. Do you have any questions for me?", hintRu: 'Назови одну-две причины, почему вакансия интересна.', sampleEn: "I like that the product is used by real people every day, and I'd like to grow into a bigger team." },
      { npcLine: "Good question. The team is eight people, fully remote. I'll send you the details by email. Thanks!", hintRu: 'Задай вопрос о команде или о следующих шагах.', sampleEn: "Yes, how big is the team, and what would the first month look like?" },
    ],
  },
]
